# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
#    driver: "gd"

    loaders:
        flysystem_loader:
            flysystem:
                filesystem_service: oneup_flysystem.public_uploads_filesystem_filesystem

    # default loader to use for all filter sets
    data_loader: flysystem_loader

    resolvers:
        flysystem_resolver:
            flysystem:
                filesystem_service: oneup_flysystem.public_uploads_filesystem_filesystem
                root_url: '%uploads_base_url%'
                cache_prefix: media/cache

    # default cache resolver for saving thumbnails
    cache: flysystem_resolver

    filter_sets:
        small:
            quality: 75
            filters:
                thumbnail:
                    size:          [380, 270]
                    mode:          outbound
                    allow_upscale: false

        medium:
            quality: 75
            filters:
                thumbnail:
                    size:          [800, 800]
                    mode:          outbound
                    allow_upscale: false

        avatar_thumbnail:
            quality: 75
            filters:
                thumbnail:
                    size:          [50, 50]
                    mode:          outbound
                    allow_upscale: false

        avatar_medium:
              quality: 75
              filters:
                thumbnail:
                  size:          [130, 130]
                  mode:          outbound
                  allow_upscale: false